mongodb/mongodbatlas-cloudformation-resources

ip-whitelist/cmd/resource/resource_test.go
Added a simple frame work for unit testing the handlers.
=> Test framework

CONTRIBUTING.md, README-postGA.md, README.md
Update files as we are still developing and not to a public beta.  When we are will move over the current README (likely updated w/ current README in progress).  Also add Contributing file w/ CLA link to flush out later.
@shum this is until we finish sorting this out.
=> Update README CONTRIBUTING

cluster/cmd/resource/resource.go
=> Add some validations to possible nil values

cluster/.rpdk-config, cluster/Makefile, database-user/.rpdk-config, database-user/Makefile, ip-whitelist/.rpdk-config, ip-whitelist/Makefile, project/.rpdk-config, project/Makefile
=> fix tags missing in resources

examples/project-ip-whitelist/project-ip.json, ip-whitelist/cmd/resource/resource.go, ip-whitelist/docs/README.md, ip-whitelist/docs/apikeydefinition.md, ip-whitelist/docs/whitelistdefinition.md, ip-whitelist/mongodb-atlas-projectipwhitelist.json
=> Fix IP Whitelist

.github/actions/atlas-cfn-deploy/entrypoint.sh, .github/workflows/atlas-cfn-deploy.yml
=> get actions to run local and hosted

cfn-resources/cfn-publishing-helper.config, cfn-resources/cfn-publishing-helper.sh, cfn-resources/cfn-submit-helper.config, cfn-resources/cfn-submit-helper.sh, cfn-resources/cluster/cmd/resource/resource.go, cfn-resources/cluster/docs/README.md, cfn-resources/cluster/docs/regionsconfig.md, cfn-resources/cluster/docs/replicationspec.md, cfn-resources/cluster/mongodb-atlas-cluster.json, cfn-resources/scripts/aws-cfn-resource-type-cleaner.sh, cfn-resources/scripts/aws-cfn-stack-cleaner.sh, cfn-resources/scripts/scrub-all-resource-types.sh
=> Testing updates 1

cfn-resources/README.md, cfn-resources/deploy.template.yaml
[CloudFormation] Replace S3 bucket in repo with a placeholder 
https://jira.mongodb.org/browse/INTMDB-360
=> INTMDB-360: Change s3 bucket default placeholder bucket

.github/workflows/deploy-mongodbatlas-cloudformation-resources.yml, cfn-resources/cluster/cmd/resource/resource.go
Can't set up Auto Scaling with Cluster resource #94 
https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/94
=> Fix scaling issue try to combine uses and run

cfn-resources/cfn-publishing-helper.sh
Fixed the resource type publishing script
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have added any necessary documentation (if appropriate)
- [ X] I have run `make fmt` and formatted my code
=> fix deployment script

.github/actions/atlas-cfn-deploy/entrypoint.sh, .github/workflows/publish-mongodbatlas-cloudformation-public-extensions.yml, cfn-resources/cfn-submit-helper.config, cfn-resources/cfn-submit-helper.sh, cfn-resources/cluster/cmd/resource/resource.go
INTMDB-360: Fix behavior of NumShards for replicated cluster
=> INTMDB-360: Fix behavior of NumShards for replicated cluster

.github/CODEOWNERS
This PR adds CODEOWNER so that @mongodb/apix1 will be automatically added as a reviewer for all the PRs
=> Add CODEOWNER

.github/workflows/cfn-test.yaml, cfn-resources/cfn-testing-helper.sh, cfn-resources/project/cmd/resource/resource.go, cfn-resources/project/test/cfn-test-create-inputs.sh, cfn-resources/project/test/cfn-test-delete-inputs.sh, cfn-resources/project/test/project.sample-cfn-request.json
Added cfn test workflow
Refactored Project and tested  CFN TEST using cfn-test-helper.sh
=> Adding cfn test workflow

cfn-resources/project/README.md
0. Minor formatting in PR (made directly) - can you use this format for future PR README files 
1. Line 37 - broken link (also double check that script)
2. Add new section and link to Example so users know to go here: https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/project/project.json . We should follow same folder structure as other resources (so include Example files as part of CFN-resources folder if that is how we did it) 
3. Use this PR to make any other doc updates you had in mind already not captured 
=> MongoDB::Atlas::Project Doc Updates

README.md
@martinstibbe can you help review if this update is technically all correct? this is related to https://jira.mongodb.org/browse/HELP-35736
=> INTMDB-411: IAM and Logging Guidance

examples/project-ip-access-list/ip-access-list.yaml
=> IpAccessList Example Bug

examples/private-endpoint/README.md, examples/private-endpoint/privateEndpoint.json
Updated Example + Readme to make easier for new users to use example 
=> privateEndpointExampleEdits

examples/cluster/cluster.json
=> removing keys

cfn-resources/go.mod, cfn-resources/go.sum, cfn-resources/ldap-configuration/README.md, cfn-resources/ldap-configuration/cmd/resource/resource.go, cfn-resources/ldap-verify/cmd/resource/resource.go
Fixed LDAP Configuration Delete.
Originally, because of an issue in the Go client [Issue](https://github.com/mongodb/go-client-mongodb-atlas/issues/339), we had to do a manual call to turn off the resource.
Now that the issue has been fixed, we removed the Manual call to the API, Updated the Go Client, and called the client Update function instead.
=> INTMDB-544 updated LDAP Configuration delete

cfn-resources/ldap-verify/mongodb-atlas-ldapverify.json
Fixed LDAP verify required property Typo:
the property should be GroupId
=> fixed LDAP verify required property

cdk/cdk-resources/third-party-integration/README.md
Update CDK L1 construct name in README.md for ThirdPartyIntegration for consistency
=> INTMDB-553: Update construct name in README.md for ThirdPartyIntegration

examples/private-endpoint/privateEndpoint.json
The private endpoint example file, was modified to match the new resource schema
=> Fixed Private Endpoint example file

.github/CODEOWNERS
Update CODEOWNER to use APIx-Integrations
=> Update codeowner to use APIx-Integrations

cfn-resources/cfn-publishing-helper.sh
=> fix versioning in cfn-publish-helper

cfn-resources/cfn-submit-helper.config
=> fixed env var to be use as input to cfn submit

cfn-resources/project-invitation/mongodb-atlas-projectinvitation.json, examples/project-invitation/project-invitation.json
Updated project-invitation CFN to be able to use get endpoint correctly.
=> Fix GetAtt functionality in project-invitation CFN

cfn-resources/cloud-backup-restore-jobs/cmd/resource/resource.go
CloudBackupRestoreJobs cfn test (create_list) fix
=> INTMDB 635 CloudBackupRestoreJobs  cfn test create_list fix

cfn-resources/network-peering/cmd/resource/resource.go
=> Fixed build and lint tests

examples/cloud-backup-restore-jobs/restore.json, examples/cluster/cluster.json, examples/database-user/user.json
updating examples for Cluster, DbUser and CLoudBackupRestoreJobs with profile changes
=> updating examples with profile changes

cdk/cdk-resources/encryption-at-rest/test/index.test.ts, cdk/l3-cdk-resources/atlas-basic/test/index.test.ts
This PR adds unit tests for L1 CDK Encryption at Rest and L3 CDK Atlas Basic.
**AtlasBasic:**
```bash
npx projen test                                                                                  
PASS  test/index.test.ts
✓ AtlasBasis construct should contain default properties (18 ms)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |   83.33 |    73.52 |      50 |   83.33 |
index.ts |   83.33 |    73.52 |      50 |   83.33 | 456-458
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.352 s, …
```
=> Unit Test for L1 CDK Encryption at Rest and L3 CDK Atlas Basic

cdk/cdk-resources/private-endpoint/API.md, cdk/cdk-resources/private-endpoint/src/index.ts
=> Auto gen index.ts - Private Endpoint

cdk/cdk-resources/network-container/API.md, cdk/cdk-resources/network-container/src/index.ts, cdk/cdk-resources/network-peering/API.md, cdk/cdk-resources/network-peering/src/index.ts
=> Regen network peering, container L1

cfn-resources/go.mod, cfn-resources/go.sum, cfn-resources/util/util.go
Replace digest with our fork which is able to handle improved security and some minor bug fixes
=> task: replace digest lib with our own fork

examples/cluster/cluster.json, examples/project/project.json
Updating examples to use the new profile, rather than default.
=> INTMDB-657: Fixing examples for projects & clusters

README.md
Added The Profile Api keys configuration to Readme File
=> added Profile section to main readme file

cdk/cdk-resources/private-endpoint-adl/API.md, cdk/cdk-resources/private-endpoint-adl/src/index.ts, cdk/cdk-resources/private-endpoint-adl/test/index.test.ts, cdk/cdk-resources/private-endpoint-adl/yarn.lock, cdk/cdk-resources/private-endpoint-regional-mode/API.md, cdk/cdk-resources/private-endpoint-regional-mode/package.json, cdk/cdk-resources/private-endpoint-regional-mode/src/index.ts, cdk/cdk-resources/private-endpoint-regional-mode/test/index.test.ts, cdk/cdk-resources/private-endpoint-regional-mode/yarn.lock
Regen CDK fro Private Endpoint ADL and Regional Mode
=> INTMDB 663 CDK update private endpoint ADL and Regional Mode

cdk/cdk-resources/cloud-backup-restore-jobs/API.md, cdk/cdk-resources/cloud-backup-restore-jobs/src/index.ts, cdk/cdk-resources/cloud-backup-restore-jobs/test/index.test.ts, cdk/cdk-resources/project-invitation/API.md, cdk/cdk-resources/project-invitation/src/index.ts, cdk/cdk-resources/project-invitation/test/index.test.ts, cdk/cdk-resources/search-index/API.md, cdk/cdk-resources/search-index/src/index.ts, cdk/cdk-resources/search-index/test/index.test.ts, cdk/cdk-resources/teams/API.md, cdk/cdk-resources/teams/src/index.ts, cdk/cdk-resources/teams/test/index.test.ts
Regen CDK for 
project-invitation
search-index
teams
cloud-backup-restore-jobs
=> Regen CDK for project-invitation search-index teams cloud-backup-restore-jobs

cdk/cdk-resources/custom-db-role/API.md, cdk/cdk-resources/custom-db-role/src/index.ts, cdk/cdk-resources/custom-dns-configuration-cluster-aws/API.md, cdk/cdk-resources/custom-dns-configuration-cluster-aws/src/index.ts, cdk/cdk-resources/datalakes/API.md, cdk/cdk-resources/datalakes/src/index.ts, cdk/cdk-resources/encryption-at-rest/API.md, cdk/cdk-resources/encryption-at-rest/src/index.ts, cdk/cdk-resources/third-party-integration/API.md, cdk/cdk-resources/third-party-integration/src/index.ts
=> Regen custom-db-role, dns config, datalakes, thirdparty int, encryption at rest

cdk/cdk-resources/global-cluster-config/API.md, cdk/cdk-resources/global-cluster-config/src/index.ts, cdk/cdk-resources/maintenance-window/API.md, cdk/cdk-resources/maintenance-window/src/index.ts, cdk/cdk-resources/online-archive/API.md, cdk/cdk-resources/online-archive/src/index.ts, cdk/cdk-resources/org-invitation/API.md, cdk/cdk-resources/org-invitation/src/index.ts
=> Regen Updated global-cluster, maint wind, ol9-arch, org-invite

cdk/cdk-resources/cloud-backup-schedule/API.md, cdk/cdk-resources/cloud-backup-schedule/src/index.ts, cdk/cdk-resources/cloud-backup-snapshot-export-bucket/API.md, cdk/cdk-resources/cloud-backup-snapshot-export-bucket/src/index.ts, cdk/cdk-resources/cloud-backup-snapshot/API.md, cdk/cdk-resources/cloud-backup-snapshot/src/index.ts
=> Regen cloud-backup-schedule, snapshot, export

cfn-resources/alert-configuration/cmd/resource/resource.go, cfn-resources/database-user/cmd/resource/resource.go, cfn-resources/global-cluster-config/cmd/resource/resource.go, cfn-resources/go.mod, cfn-resources/ldap-configuration/cmd/resource/resource.go, cfn-resources/serverless-instance/cmd/resource/resource.go, cfn-resources/x509-authentication-database-user/cmd/resource/resource.go
=> Remove pointy as direct dependency and rely on aws library

cfn-resources/alert-configuration/test/inputs_1_create.template.json, examples/alert-configuration/alert-configuration.json
Update CFN alert-configuration example to use GetAtt to demonstrate usage.
=> Update CFN alert-configuration example to use GetAtt

CODE_OF_CONDUCT.md
=> INTMDB-679: Create CODE_OF_CONDUCT.md

README.md
Adding GitHub action badges on README
=> INTMDB-691: [CFN-PI] Adding GitHub action badges on README

cfn-resources/maintenance-window/test/README.md, cfn-resources/maintenance-window/test/inputs_1_create.template.json, cfn-resources/maintenance-window/test/inputs_1_invalid.template.json, cfn-resources/maintenance-window/test/inputs_1_update.template.json, cfn-resources/project-invitation/test/README.md, cfn-resources/teams/README.md, cfn-resources/teams/test/README.md, cfn-resources/third-party-integration/test/README.md, examples/maintenance-window/maintenance-window.json, examples/teams/teams.json
Add manual QA READMEs for Teams, Third-party-integration, maintenance-window, project-invitation CFNs
=> Add manual QA READMEs for Teams, Third-party-integration, maintenance-window, project-invitation CFNs

cfn-resources/auditing/test/README.md, cfn-resources/cloud-backup-schedule/test/README.md, examples/auditing/auditing.json, examples/cloud-backup-schedule/cloudBackupSchedule.json
=> INTMDB-692: [CFN-PI] Add README.md to auditing and Cloud backup schedule

cfn-resources/cloud-backup-snapshot-export-bucket/test/README.md, cfn-resources/custom-db-role/test/README.md, examples/cloud-backup-snapshot-export-bucket/CloudBackupSnapshotExportBucket.json, examples/custom-db-role/custom-db-role.json
=> INTMDB-692: [CFN-PI] Add README.md to DB Roles and CloudBackupSnapshotExportBucket

cfn-resources/datalakes/test/README.md, cfn-resources/encryption-at-rest/test/README.md, examples/data-lakes/datalake.json
This PR adds the `README.md` with the manual steps to test Encryption at rest and Datalake
=> INTMDB-692: [CFN-PI] Add README.md to Encryption at rest and Datalake

cfn-resources/custom-dns-configuration-cluster-aws/test/README.md, cfn-resources/online-archive/test/README.md, cfn-resources/online-archive/test/cfn-test-create-inputs.sh, examples/online-archive/online-archive.json
Add manual QA README for online-archive and AWS custom-dns-config CFN
=> INTMDB-699: Add manual QA README for online-archive and AWS custom-dns-config CFN

cfn-resources/serverless-instance/test/README.md, examples/serverless-instance/serverless-instance.json
=> INTMDB-699: Add manual QA README for serverless-instance CFN

cdk/l3-cdk-resources/atlas-basic/README.md
The L3 Atlas Basic is modified to reflect the CDK profile changes
=> Issue/Fixed CDK L3 Atlas Basic Readme example

cfn-resources/private-endpoint-regional-mode/README.md, cfn-resources/private-endpoint-regional-mode/test/README.md, cfn-resources/private-endpoint-regional-mode/test/private-endpoint-regional-mode.create-sample-cfn-request.sh, cfn-resources/private-endpoint-regional-mode/test/private-endpoint-regional-mode.sample-cfn-request.json, cfn-resources/search-index/test/README.md, cfn-resources/search-index/test/cfn-test-create-inputs.sh
Add manual QA README for search-index and private-endpoint-regional CFNs
=> INTMDB-699: Add manual QA README for search-index and private-endpoint-regional CFNs

cfn-resources/network-container/test/README.md, cfn-resources/network-peering/test/README.md, examples/network-container/container.json, examples/network-peering/peering.json
=> INTMDB-692: [CFN-PI] Add README.md to Network container and Network Peering

.github/pull_request_template.md
Add a checklist for manual QA to PR template for this repository.
=> Add Manual QA checklist to PR template

cdk/cdk-resources/federated-settings-org-role-mapping/test/README.md, cdk/cdk-resources/ldap-configuration/test/README.md, cdk/cdk-resources/ldap-verify/test/README.md, cdk/cdk-resources/org-invitation/test/README.md, cdk/cdk-resources/private-endpoint-adl/test/README.md, cdk/cdk-resources/private-endpoint/test/README.md, cdk/cdk-resources/trigger/test/README.md, cdk/cdk-resources/x509-authentication-database-user/test/README.md, cfn-resources/federated-settings-org-role-mapping/test/README.md, cfn-resources/org-invitation/test/README.md, cfn-resources/private-endpoint-adl/test/README.md, cfn-resources/private-endpoint/test/README.md
_Jira ticket:_ [INTMDB-702](https://jira.mongodb.org/browse/INTMDB-702)
Add manual QA readme for special-case CDK resources
expected)
works in Atlas
=> Add manual QA readme for special-case CDK resources

cdk/cdk-resources/alert-configuration/test/README.md, cdk/cdk-resources/custom-dns-configuration-cluster-aws/test/README.md, cdk/cdk-resources/maintenance-window/test/README.md, cdk/cdk-resources/online-archive/test/README.md, cdk/cdk-resources/private-endpoint-regional-mode/test/README.md, cdk/cdk-resources/project-invitation/test/README.md, cdk/cdk-resources/search-index/test/README.md, cdk/cdk-resources/serverless-instance/test/README.md, cdk/cdk-resources/teams/test/README.md, cdk/cdk-resources/third-party-integration/test/README.md, cfn-resources/custom-dns-configuration-cluster-aws/test/README.md, cfn-resources/online-archive/test/README.md, cfn-resources/private-endpoint-regional-mode/test/README.md, cfn-resources/search-index/test/README.md, cfn-resources/serverless-instance/test/README.md, cfn-resources/teams/test/README.md, cfn-resources/third-party-integration/test/README.md
_Jira ticket:_ [INTMDB-702](https://jira.mongodb.org/browse/INTMDB-702)
Add manual QA readme for non-special-case CDK resources
expected)
works in Atlas
=> Add manual QA readme for non-special-case CDK resources

cdk/l2-cdk-resources/encryption-at-rest/test/README.md, cdk/l2-cdk-resources/third-party-integration/test/README.md, cdk/l3-cdk-resources/atlas-basic/test/README.md, cdk/l3-cdk-resources/atlas-private-endpoint/test/README.md, cdk/l3-cdk-resources/encryption-at-rest-express/test/README.md
_Jira ticket:_ [INTMDB-702](https://jira.mongodb.org/browse/INTMDB-702)
Add manual QA READMEs for CDK L2 and L3 constructs
expected)
works in Atlas
=> [INTMDB-702]: Add manual QA READMEs for CDK L2 and L3 constructs

cdk/cdk-resources/global-cluster-config/test/README.md, cfn-resources/global-cluster-config/test/README.md, cfn-resources/global-cluster-config/test/cfn-test-create-inputs.sh
Jira ticket: [INTMDB-702](https://jira.mongodb.org/browse/INTMDB-702)
Add manual QA readme for global-cluster-config (CDK & CFN)
expected)
works in Atlas
=> Add manual QA readme for global-cluster-config (CDK & CFN)

cfn-resources/search-index/test/cfn-test-delete-inputs.sh
_Jira ticket:_ INTMDB-714:
Issue: while releasing the search-index resource I got the following error:
`./test/cfn-test-delete-inputs.sh: line 26: status: unbound variable`
This PR fixed the issue in `./test/cfn-test-delete-inputs.sh`
expected)
works in Atlas
=> INTMDB-714: fix release error while deleting cluster

.github/workflows/code-health.yaml, examples/LDAPVerify/LDAPVerify.json, examples/cloud-backup-schedule/cloudBackupSchedule.json, examples/cluster/cluster.json, examples/database-user/scramUser.json, examples/database-user/x509User.json, examples/thirdpartyintegrations/prometheus.json, examples/x509-authentication-db-user/x509-authentication-db-user.json
_Jira ticket:_ [INTMDB-719](https://jira.mongodb.org/browse/INTMDB-719)
This PR adds [CFN-LINT](https://github.com/aws-cloudformation/cfn-lint) to the Code health to check that the templates in the `example` folder comply with CFN specifications
expected)
works in Atlas
=> INTMDB-719: [CFN-PI] Add CFN-lint action

README.md, examples/execution-role.yaml
_Jira ticket:_ INTMDB-743
Several customers are hitting the `CREATE_IN_PROGRESS` issue and we should make sure to highlight this issue and how to fix it. 
Example of customers hitting this issue:
* https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/506
* https://github.com/aws-quickstart/quickstart-mongodb-atlas/issues/31#issuecomment-1499313698
**This PR update the README to include how to fix this issue.** See [README](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/INTMDB-743#error-the-cfn-stack-remains-in-the-create_in_progress-state-before-failing-after-an-hour-or-so)
expected)
works in Atlas
=> INTMDB-743: [CFN-PI] Update the troubleshooting section in the readme to include common errors

cfn-resources/project-ip-access-list/cmd/resource/resource.go, cfn-resources/project-ip-access-list/mongodb-atlas-projectipaccesslist.json, cfn-resources/project-ip-access-list/test/inputs_1_update.template.json
_Jira ticket:_ INTMDB-745
Link to any related issue(s): #508
Issue: The UPDATE handler does not allow removing an entry on the access-list.
expected)
works in Atlas
**contract testing**
```bash
cfn test
================================================================================= 10 passed, 2 skipped, 12 deselected, 1 warning in 72.98s (0:01:12) ==================================================================================
```
**Manual QA using CDK**
```ts
new CfnProjectIpAccessList(this, `AtlasProjectIpAccessList`, {
profile: "default-cfn-andrea-angiolillo",
projectId: "63f4d4a47baeac59406dc131",
accessList: [
{
ipAddress: '10.1.2.9/8',
comment: 'any 3',
},
{
ipAddress: '10.1.1.9/8',
comment: 'any 1',
},
{
ipAddress: '10.1.0.9/8',
comment: 'any 2',
},
],
})
```
**Scenario:**
- …
=> INTMDB-745: [CFN-PI] Unable to update ProjectIPAccessList IPs

.github/workflows/issues.yaml
_Jira ticket:_ INTMDB-749
Follow-up PR of https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/515: Unfortunately, we cannot use atlassian actions as they do not support a self-hosted JIRA server. This PR updates the issue action to call the JIRA endpoint to create the ticket.
I was able to test the action in my personal repository. The action created this JIRA ticket: [INTMDB-760](https://jira.mongodb.org/browse/INTMDB-760)
expected)
works in Atlas
=> INTMDB-749: [CFN-PI] GitHub Action to create JIRA ticket from repo issues

README.md
_Jira ticket:_ INTMDB-799
This PR updates the examples in the README.md to include the quotes for the profile.
expected)
works in Atlas
=> INTMDB-799: [CFN-PI] Update the Profile examples to include quotes

cfn-resources/go.mod, cfn-resources/go.sum
_Jira ticket:_ [INTMDB-809](https://jira.mongodb.org/browse/INTMDB-809)
Upgrading Atlas go-client to add fix for https://jira.mongodb.org/browse/INTMDB-809
expected)
works in Atlas
=> INTMDB-809: upgrade atlas go-client

.github/workflows/contract-testing.yaml, .github/workflows/e2e-testing.yaml, cfn-resources/project/README.md
Updating our secrets management for tests.
Manual run to confirm credentials are working: https://github.com/mongodb/mongodbatlas-cloudformation-resources/actions/runs/5068257266/jobs/9100338934
_Jira ticket:_ INTMDB-686
works in Atlas
=> INTMDB-686: Updating E2E settings

README.md
Updating CDK readme link to the new cdk repo
_Jira ticket:_ INTMDB-841
=> INTMDB-841: updating cdk links

.github/workflows/issues.yaml
_Jira ticket:_ INTMDB-883
Follow-up PR of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1255
expected)
works in Atlas
=> INTMDB-883: Fix "Create JIRA ticket" Action

cfn-resources/serverless-instance/README.md, cfn-resources/serverless-instance/test/README.md
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-29453
expected)
works in Atlas
=> DOCSP-29453 Clean up serverless-instance docs

cfn-resources/org-invitation/README.md, cfn-resources/org-invitation/test/README.md
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-29443
expected)
works in Atlas
=> DOCSP-29443 Clean up org-invite docs

cfn-resources/x509-authentication-database-user/README.md
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-29458
Edit documentation for X509 certificates resources.
expected)
works in Atlas
=> DOCSP-29458 Edit x509-authentication-database-user

cfn-resources/project-ip-access-list/README.md, cfn-resources/project-ip-access-list/test/README.md
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-29449
expected)
works in Atlas
=> DOCSP-29449 Clean up project-ip-access-list docs

cfn-resources/ldap-configuration/README.md, cfn-resources/ldap-configuration/test/README.md
_Jira ticket:_ https://jira.mongodb.org/browse/DOCSP-29435
expected)
works in Atlas
=> DOCSP-29435 Clean up ldap-configuration docs

cfn-resources/global-cluster-config/cmd/resource/resource.go, cfn-resources/global-cluster-config/docs/README.md, cfn-resources/global-cluster-config/mongodb-atlas-globalclusterconfig.json, cfn-resources/global-cluster-config/test/inputs_1_create.template.json, cfn-resources/global-cluster-config/test/inputs_1_invalid.template.json, cfn-resources/teams/docs/README.md, cfn-resources/teams/mongodb-atlas-teams.json
ReadOnly properties were refactor for the next respource
- Global Cluster Config:
- CustomZoneMappings: Array of objects, cannot be read
- Teams:
- Users: Array of objects, cannot be read
##JiraTicket:
[INTMDB-700](https://jira.mongodb.org/browse/INTMDB-700)
##Test Runned
Global Cluster Config
Teams
expected)
works in Atlas
=> INTMDB-700 Part 2 Global Cluster Config Teams

cfn-resources/project-invitation/README.md
This PR is patterned on https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/543.
Jira ticket: https://jira.mongodb.org/browse/DOCSP-29448
expected)
works in Atlas
=> DOCSP-29448: Cleanup project-invitation resource README

.github/workflows/pull-request-lint.yml, CONTRIBUTING.md
_Jira ticket:_ [INTMDB-934](https://jira.mongodb.org/browse/INTMDB-934)
This PR adds a GitHub action to check that the PR follows [Conventional Commits](https://www.conventionalcommits.org/).
See [CONTRIBUTING.md](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/INTMDB-934/CONTRIBUTING.md#pr-title-format) for a full list of available formats.
**Summary of the format to use:**
- `fix: description of the ticket`: this correlates with [PATCH](http://semver.org/#summary) in Semantic Versioning
- `feat: description of the ticket`: this correlates with [MINOR](http://semver.org/#summary) in Semantic Versioning
- `BREAKING CHANGE`: a commit that has a footer `BREAKING CHANGE:` or appends a `!` after the type/scope, introduces a breaking API change (correlating with …
=> ci: Add PR lint to repo

cfn-resources/alert-configuration/cmd/resource/model.go, cfn-resources/alert-configuration/cmd/resource/resource.go, cfn-resources/alert-configuration/docs/notificationview.md, cfn-resources/alert-configuration/mongodb-atlas-alertconfiguration.json
Fixed Null pointer on OpsGenie Alert configuration integration
Added DelayMin to create flow
Testing:
_Jira ticket:_ 
- [INTMDB-819](https://jira.mongodb.org/browse/INTMDB-819)
- [INTMDB-824](https://jira.mongodb.org/browse/INTMDB-824)
expected)
works in Atlas
=> feat: INTMDB-819 / INTMDB-824 Fixed Alert Configuration OpsGenie integration null pointer error

cfn-resources/database-user/cmd/resource/resource.go, cfn-resources/database-user/docs/labeldefinition.md, cfn-resources/database-user/docs/roledefinition.md, cfn-resources/database-user/docs/scopedefinition.md
checking the ticket INTMDB-890 (this pr does not fixes any related to the Issue) i found many code problems within DatabaseUser, so i decided to make some code cleanup:
- there were mistakes between the use of errors and event progress, so in many cases the logic was throwing null pointer
- removed many unused logs
- this logic was comparing pointers instead of values, leading to unwanted behaviours: 
``` go
if (currentModel.LdapAuthType == &none) && (currentModel.AWSIAMType == &none) && (currentModel.X509Type == &none)
```
Jira tickets: 
- [INTMDB-818](https://jira.mongodb.org/browse/INTMDB-818)
- [INTMDB-815](https://jira.mongodb.org/browse/INTMDB-815)
expected)
works in Atlas
=> fix: INTMDB-890 / INTMDB-815 DatabaseUser Refactors and clean code

cfn-resources/go.mod, cfn-resources/go.sum, cfn-resources/util/util.go
expected)
works in Atlas
Added new atlas sdk client
Removed unused Secrets Put and Delete code from Util
=> feat: intmdb 953 new atlas sdk client

.github/dependabot.yml
This PR adds the `chore` prefix to the dependabot PRs to make the PR linter happy 
expected)
works in Atlas
=> fix: add prefix to dependabot PR

cfn-resources/trigger/cmd/resource/model.go, cfn-resources/trigger/cmd/resource/resource.go, cfn-resources/trigger/docs/databaseconfig.md, cfn-resources/trigger/mongodb-atlas-trigger.json, cfn-resources/trigger/resource-role.yaml
Added project property to Trigger resource:
Testing:
Ive created a stack with a projection statement:
and use the API to validate the resoult
_Jira ticket:_ [HELP-48343](https://jira.mongodb.org/browse/HELP-48343)
expected)
works in Atlas
=> feat: HELP-48343 added project propertie to trigger

cfn-resources/private-endpoint/cmd/resource/steps/awsvpcendpoint/aws_vpc_endpoint.go, cfn-resources/private-endpoint/test/private-endpoint.sample-cfn-request.json
Added validation to region to match AWS region. 
_Jira ticket:_ CLOUDP-# [INTMDB-989](https://jira.mongodb.org/browse/INTMDB-989)
expected)
works in Atlas
=> fix: INTMDB-989 Added validation to aws region

.github/workflows/cleanup-test-env.yml, .github/workflows/contract-testing.yaml, scripts/cleanup-test-env.sh
This PR adds a github action to clean up the test env to avoid exceeding the project limit in MongoDB Atlas
Follow-up of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1379
expected)
works in Atlas
=> feat: add cleanup action

CONTRIBUTING.md
This PR updates CONTRIBUTING.md to include guidelines for testing that should be followed when updating a resource.
expected)
works in Atlas
=> doc: Update CONTRIBUTING.md to include instructions for testing

README.md
Documentation update - [DOCSP-29472](https://jira.mongodb.org/browse/DOCSP-29472)
- Adds a limitations section
A markdown viewer I found online, if it's helpful for copy review: https://markdownlivepreview.com/
=> doc: Add limitations section to top level readme

.github/workflows/issues.yaml
Follow up PR of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1422
expected)
works in Atlas
=> fix: update issue.yml to use issue number as Ticket title

CONTRIBUTING.md, cfn-resources/Makefile, cfn-resources/access-list-api-key/cmd/resource/resource.go, cfn-resources/api-key/cmd/resource/resource.go, cfn-resources/api-key/test/apikey.create-sample-cfn-request.sh, cfn-resources/data-lake-pipeline/cmd/resource/resource.go, cfn-resources/federated-database-instance/cmd/resource/resource.go, cfn-resources/federated-query-limit/cmd/resource/resource.go, cfn-resources/go.mod, cfn-resources/go.sum, cfn-resources/privatelink-endpoint-service-data-federation-online-archive/cmd/resource/resource.go, cfn-resources/serverless-private-endpoint/cmd/resource/resource.go, cfn-resources/util/util.go
Update Atlas SDK to latest version and add action to update.
_Jira ticket:_ https://jira.mongodb.org/browse/INTMDB-1120
expected)
works in Atlas
=> chore: Update Atlas SDK to v20230201008

cfn-resources/organization/cmd/resource/resource.go
This PR updates the Atlas SDK version to latest in the repository.
expected)
works in Atlas
=> feat: Update Atlas SDK version in Organization resource

.github/workflows/code-health.yaml, .github/workflows/contract-testing.yaml, .github/workflows/e2e-testing.yaml
Adjust workflow configuration to properly support merge queues.
> A merge queue will wait for required checks to be reported before it can proceed with merging. You must update your CI configuration to trigger and report on merge group events when requiring a merge queue.
reference: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues
expected)
works in Atlas
=> chore: CI configuration to trigger and report on merge group events

.github/workflows/contract-testing.yaml, .github/workflows/e2e-testing.yaml
=> fix: removed contract testing and e2e testing from merge queue

cfn-resources/database-user/Makefile, cfn-resources/database-user/cmd/resource/resource.go, cfn-resources/project/cmd/resource/resource.go, cfn-resources/util/progressevent/failed_event.go, cfn-resources/util/progressevent/in_progress.go, cfn-resources/util/util.go
_Jira ticket:_ [INTMDB-1087](https://jira.mongodb.org/browse/INTMDB-1087)
Migrating DatabaseUser resource to new Atlas SDK.
expected)
works in Atlas
**Manual testing creating the stack using private registry:**
**Manual testing deleting the stack using private registry:**
=> refactor: Migrates DatabaseUser resource to new Atlas SDK

cfn-resources/online-archive/Makefile, cfn-resources/online-archive/cmd/resource/resource.go, cfn-resources/util/util.go
_Jira ticket:_ [INTMDB-1097](https://jira.mongodb.org/browse/INTMDB-1097)
Migrating OnlineArchive resource to new Atlas SDK.
expected)
works in Atlas
**Manual testing creating the stack using private registry:**
**Manual testing deleting the stack using private registry:**
=> refactor: Migrates OnlineArchive resource to new Atlas SDK

cfn-resources/teams/cmd/resource/resource.go
_Jira ticket:_ [INTMDB-1144](https://jira.mongodb.org/browse/INTMDB-1144)
The delete operation defined in teams resource was not capable of deleting a team if it was assigned to a project. The delete operation would only remove the team from the project.
expected)
works in Atlas
<details>
<summary>Contract testing</summary>
</details>
<details>
<summary>Manual testing of proper create and delete of team with a project</summary>
**Stack history**  
**Atlas UI after creation**
**Atlas UI after deleting team**
</details>
=> fix: delete operation can properly delete a team that has an associated project

examples/activate-mongodb-atlas-resources.template.yaml
_Jira ticket:_ [INTMDB-1150](https://jira.mongodb.org/browse/INTMDB-1150)
Add resource types in sample template for activation
expected)
works in Atlas
=> fix: Add missing resource types for activation

.tool-versions, CONTRIBUTING.md
_Jira ticket:_ [INTMDB-1153](https://jira.mongodb.org/browse/INTMDB-1153)
Original update was done in  [PR 632](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/632) 
expected)
works in Atlas
=> fix: Update doc to go 1.20

cfn-resources/project-ip-access-list/cmd/resource/create.go
fixed error message for Project IP Access list
_Jira ticket: [INTMDB-1057](https://jira.mongodb.org/browse/INTMDB-1057)
expected)
works in Atlas
=> fix: INTMDB-1057 fixed error message

cfn-resources/ldap-configuration/Makefile, cfn-resources/ldap-configuration/cmd/resource/resource.go, cfn-resources/ldap-configuration/docs/README.md
_Jira ticket:_ [INTMDB-1092](https://jira.mongodb.org/browse/INTMDB-1092)
Migrating LDAPConfiguration resource to new Atlas SDK.
expected)
works in Atlas
**Manual testing creating the stack using private registry:**
**Manual testing deleting the stack using private registry:**
=> refactor: Migrates LDAPConfiguration resource to new Atlas SDK

cfn-resources/third-party-integration/cmd/resource/resource.go
_Jira ticket:_ [INTMDB-1108](https://jira.mongodb.org/browse/INTMDB-1108)
expected)
works in Atlas
```bash
cfn test --function-name TestEntrypoint --verbose
=== 13 passed, 2 skipped, 9 deselected in 72.36s (0:01:12) ===
```
=> feat: migrate third-party resource to use the autogenerated Atlas SDK

.github/workflows/cfn-publish-resource.yaml, .github/workflows/cfn-publish.sh
feat: cfn publish workflow fix
JIRA Ticket: https://jira.mongodb.org/browse/INTMDB-1149
expected)
works in Atlas
=> fix: cfn Publish workflow fix

cfn-resources/alert-configuration/mongodb-atlas-alertconfiguration.json, cfn-resources/auditing/mongodb-atlas-auditing.json, cfn-resources/custom-db-role/mongodb-atlas-customdbrole.json, cfn-resources/database-user/mongodb-atlas-databaseuser.json, cfn-resources/maintenance-window/mongodb-atlas-maintenancewindow.json, cfn-resources/network-container/mongodb-atlas-networkcontainer.json, cfn-resources/online-archive/mongodb-atlas-onlinearchive.json, cfn-resources/org-invitation/mongodb-atlas-orginvitation.json, cfn-resources/project-invitation/mongodb-atlas-projectinvitation.json, cfn-resources/project-ip-access-list/mongodb-atlas-projectipaccesslist.json, cfn-resources/project/mongodb-atlas-project.json, cfn-resources/search-index/mongodb-atlas-searchindex.json, cfn-resources/serverless-instance/mongodb-atlas-serverlessinstance.json, cfn-resources/teams/mongodb-atlas-teams.json
Added documentation in schema resources:
this first PR contans all the resources that have been already updated to the new SDK so the deploy does not get delayed
Validation:
to validate all the resources ive run the next script to excecute the cfn generate in all the modified schemas:
``` bash
#!/bin/bash
current_directory=$(pwd)
for folder in "$current_directory"/*/; do
if [ -d "$folder" ]; then
echo "GENERATING ----- ${folder}"
cd "$folder"
cfn generate
cd "$current_directory"
fi
done
``` 
_Jira ticket_: [1161](https://jira.mongodb.org/browse/INTMDB-1161)
expected)
works in Atlas
=> doc: added docs to updated resources 1

cfn-resources/access-list-api-key/mongodb-atlas-accesslistapikey.json, cfn-resources/api-key/mongodb-atlas-apikey.json, cfn-resources/cloud-backup-restore-jobs/mongodb-atlas-cloudbackuprestorejobs.json, cfn-resources/cloud-backup-schedule/mongodb-atlas-cloudbackupschedule.json, cfn-resources/cloud-backup-snapshot-export-bucket/mongodb-atlas-cloudbackupsnapshotexportbucket.json, cfn-resources/cloud-backup-snapshot/mongodb-atlas-cloudbackupsnapshot.json, cfn-resources/cluster-outage-simulation/mongodb-atlas-clusteroutagesimulation.json, cfn-resources/cluster/mongodb-atlas-cluster.json, cfn-resources/custom-dns-configuration-cluster-aws/mongodb-atlas-customdnsconfigurationclusteraws.json, cfn-resources/data-lake-pipeline/mongodb-atlas-datalakepipeline.json, cfn-resources/datalakes/mongodb-atlas-datalakes.json, cfn-resources/encryption-at-rest/mongodb-atlas-encryptionatrest.json, cfn-resources/federated-database-instance/mongodb-atlas-federateddatabaseinstance.json, cfn-resources/federated-query-limit/mongodb-atlas-federatedquerylimit.json, cfn-resources/federated-settings-org-role-mapping/mongodb-atlas-federatedsettingsorgrolemapping.json, cfn-resources/global-cluster-config/mongodb-atlas-globalclusterconfig.json, cfn-resources/ldap-configuration/mongodb-atlas-ldapconfiguration.json, cfn-resources/ldap-verify/mongodb-atlas-ldapverify.json, cfn-resources/network-peering/mongodb-atlas-networkpeering.json, cfn-resources/organization/mongodb-atlas-organization.json, cfn-resources/private-endpoint-adl/mongodb-atlas-privateendpointadl.json, cfn-resources/private-endpoint-regional-mode/mongodb-atlas-privateendpointregionalmode.json, cfn-resources/privatelink-endpoint-service-data-federation-online-archive/mongodb-atlas-privatelinkendpointservicedatafederationonlinearchive.json, cfn-resources/serverless-private-endpoint/mongodb-atlas-serverlessprivateendpoint.json, cfn-resources/third-party-integration/mongodb-atlas-thirdpartyintegration.json, cfn-resources/trigger/mongodb-atlas-trigger.json, cfn-resources/x509-authentication-database-user/mongodb-atlas-x509authenticationdatabaseuser.json
Added documentation in schema resources:
this first PR contans all the resources that have been already updated to the new SDK so the deploy does not get delayed
Validation:
to validate all the resources ive run the next script to excecute the cfn generate in all the modified schemas:
``` bash
#!/bin/bash
current_directory=$(pwd)
for folder in "$current_directory"/*/; do
if [ -d "$folder" ]; then
echo "GENERATING ----- ${folder}"
cd "$folder"
cfn generate
cd "$current_directory"
fi
done
``` 
_Jira ticket_: [1161](https://jira.mongodb.org/browse/INTMDB-1161)
expected)
works in Atlas
=> doc: added docs to updated resources 2

cfn-resources/custom-dns-configuration-cluster-aws/cmd/resource/resource.go, cfn-resources/custom-dns-configuration-cluster-aws/test/inputs_1_invalid.template.json
_Jira ticket:_ [INTMDB-1085](https://jira.mongodb.org/browse/INTMDB-1085)
expected)
works in Atlas
```bash
cfn test --function-name TestEntrypoint --verbose
== 5 passed, 3 skipped, 16 deselected in 33.67s ==
```
=> feat: move CustomDnsConfigurationClusterAws to the new Atlas SDK

cfn-resources/custom-dns-configuration-cluster-aws/cmd/resource/resource.go, cfn-resources/custom-dns-configuration-cluster-aws/test/inputs_1_invalid.template.json
This PR addresses this comment https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/752#discussion_r1344407213
expected)
works in Atlas
=> feat: Addressed PR comment

cfn-resources/cloud-backup-snapshot/Makefile, cfn-resources/cloud-backup-snapshot/cmd/resource/resource.go, cfn-resources/util/util.go
_Jira ticket:_ [INTMDB-1081](https://jira.mongodb.org/browse/INTMDB-1081)
Migrating CloudBackupSnapshot resource to new Atlas SDK.
expected)
works in Atlas
```
cfn test --function-name TestEntrypoint --verbose   
7 passed, 3 skipped, 14 deselected
```
**Manual testing creating and deleting the stack using private registry:**
=> refactor: Migrates CloudBackupSnapshot resource to new Atlas SDK

cfn-resources/private-endpoint-regional-mode/cmd/resource/resource.go
_Jira ticket:_ [INTMDB-1101](https://jira.mongodb.org/browse/INTMDB-1101)
expected)
works in Atlas
```bash
cfn test --function-name TestEntrypoint --verbose
===== 7 passed, 1 skipped, 16 deselected in 46.19s ====
```
=> refactor: migrate private endpoing region to new Atlas SDK

cfn-resources/cloud-backup-schedule/Makefile, cfn-resources/cloud-backup-schedule/cmd/resource/resource.go, examples/cloud-backup-schedule/cloudBackupSchedule.json
_Jira ticket:_ [INTMDB-1082](https://jira.mongodb.org/browse/INTMDB-1082)
Migrating CloudBackupSchedule resource to new Atlas SDK.
expected)
works in Atlas
```
cfn test --function-name TestEntrypoint --verbose   
8 passed, 4 skipped, 12 deselected
```
**Manual testing creating and deleting the stack using private registry:**
=> refactor: Migrates CloudBackupSchedule resource to new Atlas SDK

cfn-resources/encryption-at-rest/Makefile, cfn-resources/encryption-at-rest/cmd/resource/resource.go
_Jira ticket:_ [INTMDB-1089](https://jira.mongodb.org/browse/INTMDB-1089)
Migrating EncryptionAtRest resource to new Atlas SDK.
expected)
works in Atlas
```
cfn test --function-name TestEntrypoint --verbose   
8 passed, 4 skipped, 12 deselected 
```
**Manual testing creating and deleting the stack using private registry:**
=> refactor: Migrates EncryptionAtRest resource to new Atlas SDK

cfn-resources/alert-configuration/cmd/resource/resource.go, cfn-resources/alert-configuration/test/alert-configuration.sample-cfn-request.json, cfn-resources/alert-configuration/test/inputs_1_create.template.json, cfn-resources/alert-configuration/test/inputs_1_update.template.json, examples/alert-configuration/alert-configuration.json
Related to [INTMDB-1078](https://jira.mongodb.org/browse/INTMDB-1078)
Detected a bug in matchers object that had a simple fix, added the field in our examples and contract testing to avoid regressions.
expected)
works in Atlas
<details>
<summary>CFN invoke to create alert configuration with matcher</summary>
```cfn invoke resource CREATE ./test/alert-configuration.sample-cfn-request.json```
Matcher that filters type name standalone is present:
</details>
<details>
<summary>Contract tests</summary>
</details>
=> fix: adjusting properties in alert config dynamic matcher object to lowercase

cfn-resources/README.md
minor updates to resource README
expected)
works in Atlas
=> fix: Update README.md

.github/workflows/issues.yaml
_Jira ticket:_ INTMDB-1190
Follow-up PR of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1526
expected)
works in Atlas
=> feat: INTMDB-1190: Update message added to github issue in the automation to create Jira ticket

cfn-resources/cloud-backup-restore-jobs/CHANGELOG.md, cfn-resources/cloud-backup-restore-jobs/Makefile, cfn-resources/cloud-backup-restore-jobs/cmd/resource/model.go, cfn-resources/cloud-backup-restore-jobs/cmd/resource/resource.go, cfn-resources/cloud-backup-restore-jobs/docs/README.md, cfn-resources/cloud-backup-restore-jobs/mongodb-atlas-cloudbackuprestorejobs.json
_Jira ticket:_ [INTMDB-1080](https://jira.mongodb.org/browse/INTMDB-1080)
Migrating CloudBackUpRestoreJobs resource to new Atlas SDK.
expected)
works in Atlas
CreatedAt is removed as it's not being sent by the server, e.g. read operation before this PR:
```
cfn invoke --function-name TestEntrypoint resource READ  test/cloud-backup-restore-job.sample-cfn-request.json                        <aws:mms-scratch> <region:us-west-2>
Resource schema is valid.
=== Handler input ===
{
"callbackContext": null,
"action": "READ",
"requestData": {
"resourceProperties": {
"ProjectId": "***",
"InstanceName": "***",
"InstanceType": "cluster",
"SnapshotId": "***",
"Id": "***",
"Profile": "default"
},
"previousResourceProperties": {}
},
"region": "us-east-1",
"awsAccountId": "***",
"bearerToken": "***"
}
=== …
```
=> refactor: Migrates CloudBackUpRestoreJobs resource to new Atlas SDK

cfn-resources/cfn-publishing-helper.sh, cfn-resources/cfn-submit-helper.sh
_Jira ticket:_ [INTMDB-1175](https://jira.mongodb.org/browse/INTMDB-1175)
Delete stack role before publishing so we are sure that role always exists.
expected)
works in Atlas
=> feat: Delete stack role before publishing

.github/workflows/cfn-publish-resource.yaml
_Jira ticket:_ [INTMDB-1220](https://jira.mongodb.org/browse/INTMDB-1220)
Shows resource and version in Github action run name.
expected)
works in Atlas
=> feat: Shows resource and version in Github action run name

cfn-resources/database-user/cmd/resource/resource.go, cfn-resources/database-user/test/databaseuser.sample-template.json, cfn-resources/database-user/test/inputs_2_create.template.json, cfn-resources/database-user/test/inputs_2_update.template.json
_Jira ticket:_ [INTMDB-1230](https://jira.mongodb.org/browse/INTMDB-1230) and [HELP-51534](https://jira.mongodb.org/browse/HELP-51534)
This change ensures that `password` field is not included in create or update requests if it is empty. Includes new contract tests for AWS IAM types.
expected)
works in Atlas
<details>
<summary>Manual testing stack using private registry</summary>
Stack creation using resource template:
Verifying Atlas UI
</details>
=> fix: avoid sending empty password property in requests for database user resource

cfn-resources/cfn-publishing-automation/cfn-3P-provider-register.yaml
Our publishing flow is currently failing to continue after the command `yum update -y` is executed in CodeBuild, more details [INTMDB-1248](https://jira.mongodb.org/browse/INTMDB-1248).
Steps I have tried:
- Included a debug level option in yum command to see if useful information was provided. From last lines it seems to stop when verifying signature of an updated library `RPM transaction start.`.
- Run `yum clean all` before running `yum update -y`.
- Use `dnf` over `yum`.
These options all came to the same problem.
**Current solution**
Since it is not crucial to have latest versions in this image, we can simply rely on versions provided in the [base image](https://github.com/aws/aws-codebuild-docker-images/tree/master/al2/x86_64/standard/5.0). With this change I was able to …
=> fix: AWS automation update v55 [remove yum upgrade command which causes execution to stop in some cases]

cfn-resources/trigger/test/README.md
we have added a simple guideline to setup a test case scenario for trigger testing
expected)
works in Atlas
=> doc: added trigger guide for creating a test case scenario

.github/pull_request_template.md
Updates our PR template and adds a required checklist to verify there are no credentials-related unsafe changes.
Link to any related issue(s): https://jira.mongodb.org/browse/INTMDB-1290
expected)
works in Atlas
=> chore: updates PR template.

.gitmodules
Removes quickstarts submodules as it's not being useful and the target repo has changed.
Jira ticket: [INTMDB-1299](https://jira.mongodb.org/browse/INTMDB-1299)
expected)
works in Atlas
=> chore: Removes quickstarts submodules

.github/workflows/issues.yaml
This PR removes the Assignee from the github action so that the created JIRA ticket is not assigned to a user.
expected)
works in Atlas
=> fix: Removes Assignee from issues.yml

.github/workflows/issues.yaml
_Jira ticket:_ CLOUDP-215192
expected)
works in Atlas
=> chore: CLOUDP-215192 - Update Automation That Creates Github Issues To Create CLOUDP rather than INTMDB

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/issues.yaml, README.md
_Jira ticket:_ CLOUDP-215956
Same PR for TF https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1767
expected)
works in Atlas
=> chore: CLOUDP-215956 - Convert our bug report issue on GitHub to forms

.github/workflows/issues.yaml
_Jira ticket:_ [CLOUDP-222765](https://jira.mongodb.org/browse/CLOUDP-222789)
The Jira automation was missing some properties to run it when reopening and closing the GitHub issues 
expected)
works in Atlas
=> chore: fix a bug with the JIRA ticket automation

.github/pull_request_template.md, .github/workflows/cfn-publish-resource.yaml, .github/workflows/cfn-test.yaml, .github/workflows/cleanup-test-env.yml, .github/workflows/code-health.yaml, .github/workflows/contract-testing.yaml, .github/workflows/deploy-mongodbatlas-cloudformation-resources.yaml, .github/workflows/e2e-testing.yaml, .github/workflows/issues.yaml, .github/workflows/launch-quickstart-mongodbatlas.yaml, .github/workflows/publish-mongodbatlas-cloudformation-public-extensions.yaml, .github/workflows/pull-request-lint.yml, .github/workflows/stale.yaml, .github/workflows/update-sdk.yml
_Jira ticket:_ [CLOUDP-221682](https://jira.mongodb.org/browse/CLOUDP-221682)
This PR pings all the GitHub actions to a specific gitsha.
Similar to TF: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1858
expected)
works in Atlas
=> chore: Ping GH actions to a GitSHA

cfn-resources/org-invitation/cmd/resource/resource.go, cfn-resources/project/cmd/resource/resource.go, cfn-resources/teams/cmd/resource/resource.go
_Jira ticket:_ CLOUDP-226564
When configuring an incorrect profile
Before: "runtime error: invalid memory address or nil pointer dereference"
Now: "ResourceNotFoundException: Secrets Manager can't find the specified secret.”
This came for a HELP ticket that was using project resource, but saw the same pattern in org-invitation and teams resources as well.
Tested the fix by doing a private publish of project resource.
expected)
works in Atlas
=> fix: Improves error message when API client cannot be created due to incorrect profile

.github/workflows/cleanup-test-env.yml, scripts/cleanup-test-env.sh
Fixes test cleanup process. It follows the same approach as in Terraform project
expected)
works in Atlas
=> chore: Fixes test cleanup process

.github/workflows/contract-testing.yaml
=> chore: Updates atlas-github-action for contract tests

cfn-resources/search-deployment/docs/README.md, cfn-resources/search-deployment/docs/apisearchdeploymentspec.md, cfn-resources/search-deployment/mongodb-atlas-searchdeployment.json
_Jira ticket:_ CLOUDP-234048
expected)
works in Atlas
=> doc: Adds documentation to new `SearchDeployment` resource 

CONTRIBUTING.md, cfn-resources/search-deployment/cmd/resource/mappings.go, cfn-resources/search-deployment/cmd/resource/mappings_test.go, cfn-resources/search-deployment/cmd/resource/resource.go, cfn-resources/search-deployment/cmd/resource/state_transition.go, cfn-resources/search-deployment/cmd/resource/state_transition_test.go, cfn-resources/stream-connection/cmd/resource/mappings.go, cfn-resources/stream-connection/cmd/resource/mappings_test.go, cfn-resources/stream-connection/cmd/resource/resource.go, cfn-resources/stream-instance/cmd/resource/mappings.go, cfn-resources/stream-instance/cmd/resource/mappings_test.go, cfn-resources/stream-instance/cmd/resource/resource.go
Adjusts unit test package to convention used in our terraform repository.
expected)
works in Atlas
=> chore: Define unit tests within test package and adjust guidelines

cfn-resources/stream-connection/cmd/resource/mappings_test.go, cfn-resources/stream-connection/docs/README.md, cfn-resources/stream-connection/docs/streamskafkaauthentication.md, cfn-resources/stream-connection/mongodb-atlas-streamconnection.json, cfn-resources/stream-connection/test/cfn-test-create-inputs.sh, cfn-resources/stream-connection/test/inputs_3_create.json, cfn-resources/stream-connection/test/inputs_3_update.json, examples/atlas-streams/stream-connection/sample-stream-connection.json
Adds Stream Connection Sample type
CLOUDP-234642
expected)
`cfn test`
manual stack create
manual stack delete
atlas UI validation
works in Atlas
=> feat: Adds Stream Connection Sample type

README.md
_Jira ticket:_ CLOUDP-240373 (associated to https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/982)
Adds a note for using KMS keys to encrypt the profile secret. Findings for handling this use case can be seen in HELP-55019.
expected)
works in Atlas
=> doc: Includes note for using a KMS key to encrypt the profile secret

cfn-resources/scripts/update-sdk.sh
Including improvement that was added in terraform repo: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/2028/files#diff-ac43119d95afef33dec7ebd5a2833518337fa7689f13059049b2f919185f376f
expected)
works in Atlas
=> chore: Improvement in update sdk script to modify mockery config file

cfn-resources/stream-connection/README.md, cfn-resources/stream-connection/docs/README.md, cfn-resources/stream-connection/mongodb-atlas-streamconnection.json, cfn-resources/stream-instance/README.md, cfn-resources/stream-instance/mongodb-atlas-streaminstance.json, examples/atlas-streams/README.md
Updates GA status for Atlas Stream resources
_Jira ticket:_ CLOUDP-237009
expected)
works in Atlas
=> feat: Updates GA status for Atlas Stream resources

cfn-resources/private-endpoint-aws/docs/README.md, cfn-resources/private-endpoint-aws/mongodb-atlas-privateendpointaws.json, cfn-resources/private-endpoint-service/docs/README.md, cfn-resources/private-endpoint-service/mongodb-atlas-privateendpointservice.json, cfn-resources/trigger/mongodb-atlas-trigger.json
Fixes profile link
expected)
works in Atlas
=> doc: Fixes profile link

Makefile, cfn-resources/alert-configuration/mongodb-atlas-alertconfiguration.json
Based on https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/319, we need to update the list of `matchers`
[Looking in TF](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/486298b8874bce44914d959f87b9b7e780678a6f/internal/service/alertconfiguration/resource_alert_configuration.go#L157), should we actually remove this enum and just leave it open as `string`?
_Jira ticket:_ CLOUDP-261730
expected)
works in Atlas
=> fix: Adds missing matchers for the alert_configuration resource.

cfn-resources/encryption-at-rest/cmd/resource/resource.go, cfn-resources/util/constants/constants.go
Adds `Config` to paths for validating required fields
expected)
works in Atlas
=> fix: Adds `Config` to paths for validating required fields

README.md
Corrects spelling typo 
expected)
works in Atlas
=> doc: Typo in Readme

.github/workflows/cfn-publish-resource.yaml, .github/workflows/publish.yaml
Creates new publishing system
_Jira ticket:_  CLOUDP-215089
expected)
works in Atlas
=> chore: Creates new publishing system

README.md, examples/README.md
Updates documentation on getting started and adds a section to configure KMS Key Policy
Link to any related issue(s): CLOUDP-265784
expected)
works in Atlas
=> doc: Updates documentation on getting started and adds a section to configure KMS Key Policy

.github/workflows/code-health.yaml, .tool-versions, CONTRIBUTING.md, Makefile, cfn-resources/.golangci.yml, cfn-resources/go.mod, cfn-resources/go.sum
Updates Go to 1.23. 
Also change:
- Temporarily skip Go Linter as there are some linter issues when updating to Go 1.23. They'll be fixed in a following PR so this PR keeps focused on Go update. 
- Updates Mock generation as current version fails with Go 1.23:
```
INF Starting mockery dry-run=false version=v2.38.0
INF Using config: /.../mongodbatlas-cloudformation-resources/cfn-resources/.mockery.yaml dry-run=false version=v2.38.0
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=...]
```
_Jira ticket:_ CLOUDP-215160
Link to …
=> chore: Updates Go to 1.23

.github/workflows/contract-testing.yaml, cfn-resources/access-list-api-key/cmd/resource/resource.go, cfn-resources/alert-configuration/cmd/resource/resource.go, cfn-resources/api-key/cmd/resource/resource.go, cfn-resources/auditing/cmd/resource/resource.go, cfn-resources/cloud-backup-restore-jobs/cmd/resource/resource.go, cfn-resources/cloud-backup-schedule/cmd/resource/resource.go, cfn-resources/cluster-outage-simulation/cmd/resource/resource.go, cfn-resources/cluster/cmd/resource/resource.go, cfn-resources/data-lake-pipeline/cmd/resource/resource.go, cfn-resources/database-user/cmd/resource/resource.go, cfn-resources/federated-database-instance/cmd/resource/resource.go, cfn-resources/federated-query-limit/cmd/resource/resource.go, cfn-resources/go.mod, cfn-resources/go.sum, cfn-resources/online-archive/cmd/resource/resource.go, cfn-resources/organization/cmd/resource/resource.go, cfn-resources/private-endpoint-adl/cmd/resource/resource.go, cfn-resources/private-endpoint-aws/cmd/resource/resource.go, cfn-resources/private-endpoint-regional-mode/cmd/resource/resource.go, cfn-resources/private-endpoint-service/cmd/resource/resource.go, cfn-resources/privatelink-endpoint-service-data-federation-online-archive/cmd/resource/resource.go, cfn-resources/project/cmd/resource/resource.go, cfn-resources/search-deployment/cmd/resource/resource.go, cfn-resources/serverless-private-endpoint/cmd/resource/resource.go, cfn-resources/stream-connection/cmd/resource/resource.go, cfn-resources/stream-instance/cmd/resource/resource.go, cfn-resources/test/e2e/utility/atlas_helper.go, cfn-resources/util/util.go
Adds the latest version of the SDK
Link to any related issue(s): CLOUDP-272612
expected)
works in Atlas
=> chore: Adds latest SDK version so that it can be used for new resources 

.github/workflows/contract-testing.yaml, cfn-resources/resource-policy/test/cfn-test-create-inputs.sh, cfn-resources/resource-policy/test/contract-testing/cfn-test-create-inputs.sh
Removes unnecessary checks in input generation
expected)
works in Atlas
=> chore: Removes unnecessary checks in input generation

cfn-resources/resource-policy/README.md, cfn-resources/resource-policy/mongodb-atlas-resourcepolicy.json
Documentation
expected)
works in Atlas
=> doc: ResourcePolicy documentation

.tool-versions, cfn-resources/go.mod
Updates Go to 1.23.1
expected)
works in Atlas
=> chore: Updates Go to 1.23.1

cfn-resources/resource-policy/README.md
Uses consistent Private Preview
Link to any related issue(s): CLOUDP-277628
expected)
works in Atlas
=> doc: Uses consistent Private Preview

examples/cluster/free-tier-M0-cluster.json
Removes analytics specs from cluster free example
Link to any related issue(s):  based on [internal discussion](https://mongodb.slack.com/archives/CTFQM1ZFB/p1729739160924629)
expected)
works in Atlas
Screenshot CFN
Screenshot Atlas
=> chore: Removes analytics specs from cluster free example

.github/workflows/issues.yaml
chore: Adds JIRA prefix for GitHub issues
expected)
works in Atlas
=> chore: Adds JIRA prefix for GitHub issues

cfn-resources/resource-policy/README.md
_Jira ticket:_ [CLOUDP-#290399](https://jira.mongodb.org/browse/CLOUDP-290399)
expected)
works in Atlas
=> doc: Updates for Public Preview.

.github/workflows/update-sdk.yml
Removes use of verify-changed-files GitHub action as it's not needed.  As in [peter-evans/create-pull-request GHA](https://github.com/peter-evans/create-pull-request) doc:
```
If there are no changes (i.e. no diff exists with the checked-out base branch), no pull request will be created and the action exits silently.
```
_Jira ticket:_ CLOUDP-306815
expected)
works in Atlas
=> chore: Removes use of verify-changed-files GitHub action

.github/dependabot.yml
See https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/1353#issuecomment-2893131701
expected)
works in Atlas
=> chore: Removes `reviewers` field in the `dependabot.yml` as it is being removed in favor of CODEOWNERS
