mongodb/mongodbatlas-cloudformation-resources

- cfn-resources/cluster/cmd/resource/resource.go
- [ x] Bug fix (non-breaking change which fixes an issue)
#94 
- [ x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added any necessary documentation (if appropriate)
- [ x] I have run `make fmt` and formatted my code
This adds the model settings to the providerSettings.
> add cluster data to provider settings

- cfn-resources/network-peering/cmd/resource/model.go
- cfn-resources/network-peering/cmd/resource/resource.go
- cfn-resources/network-peering/docs/README.md
…r discussion with team and internal meetings,
we support only "AWS" as provider while deploying through cloudformation scripts.
- [ ✅ Bug fix (non-breaking change which fixes an issue)
- [✅] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
1. Provider Name is fixed constant "AWS". As per discussion with team and internal meetings,
we support only "AWS" as provider while deploying through cloudformation scripts.
2. Documentation update w.r.t to latest [Atlas Admin OpenAPI Documenation](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Network-Peering-Connections)
3. Addressing #149, #139
> Bug Fix Network peering

- .github/workflows/check-copyright.yml
- .github/workflows/gobuild.yml
- .github/workflows/golint.yml
Updated gitActions to run only on pull requests + master and not push
**Before:**
**After:**
> Updated gitActions to run only on pull request and not push

- cdk/l2-cdk-resources/encryption-at-rest/.projen/deps.json
- cdk/l2-cdk-resources/encryption-at-rest/.projen/tasks.json
- cdk/l2-cdk-resources/encryption-at-rest/.projenrc.js
- cdk/l2-cdk-resources/encryption-at-rest/API.md
- cdk/l2-cdk-resources/encryption-at-rest/package.json
- cdk/l2-cdk-resources/encryption-at-rest/src/index.ts
- cdk/l2-cdk-resources/encryption-at-rest/yarn.lock
Issue: When running `npx project build` we are getting
```
build » compile | jsii --silence-warnings=reserved-word
warning JSII6: A "peerDependency" on "@mongodbatlas-awscdk/encryption-at-rest" at "^1.0.1" means you should take a "devDependency" on "@mongodbatlas-awscdk/encryption-at-rest" at "1.0.1" (found "^1.0.1")
```
This PR fixes this issue by pinging the version of `encryption-at-rest` at `v1.0.1`
> INTMDB-573: fixed warning JSII6

- cdk/cdk.sh
Updated the `cdk.sh` to generate L1, L2 and L3 CDK contractors. 
```bash
#
```
<details>
<summary>Create L1 CDK constructor</summary>
```bash
./cdk.sh cluster L1                                                                                                                16.18.0 bazel 5.4.0
Generating L1 CDK resource
generating for MongoDB::Atlas::Cluster
cluster
Unresolvable read-only property (attribute) MongoDB::Atlas::Cluster.ConnectionStrings/Standard
Unresolvable read-only property (attribute) MongoDB::Atlas::Cluster.ConnectionStrings/StandardSrv
Unresolvable read-only property (attribute) MongoDB::Atlas::Cluster.ConnectionStrings/Private
Unresolvable read-only property (attribute) MongoDB::Atlas::Cluster.ConnectionStrings/PrivateSrv …
```
> INTMDB-583: Update cdk.sh to create L2 and L3 CDK project as well

- cfn-resources/third-party-integration/mongodb-atlas-thirdpartyintegration.json
The ThirdPartyIntegration CFN currently uses only “Type” as the primaryIdentifier. This would mean we can’t create same type of integrations for different projects from the same stack.
As a fix, we are adding ProjectId to the PrimaryIdentifier for this resource in addition to "(Integration)Type"
Testing:
Ran tests locally against Atlas account and project:
> INTMDB-578: add ProjectId to PrimaryIdentifier for ThirdPartyIntegration CFN

- cfn-resources/third-party-integration/test/cfn-test-create-inputs.sh
Change ATLAS keys env variables in test-create-input script for third party integration CFN resource.
> Update env variables from MCLI to ATLAS

- cfn-resources/cfn-submit-helper.sh
- cfn-resources/project/test/cfn-test-create-inputs.sh
- cfn-resources/project/test/templates/inputs_1_create.template.json
While running `cfn test` for the project resource I run into some issues in generating the input file. This PR updates the script to use the new location of the template files/
> Update script to use template folder

- cfn-resources/teams/docs/README.md
- cfn-resources/teams/mongodb-atlas-teams.json
- examples/teams/teams.json
While trying to use GetAttr of the TeamId field I got the following errors: OrgId required in order to run the Get endpoint.
This PR updates the resource definition to include the orgId
> Updated teams resource to work with getAttr

- cfn-resources/cloud-backup-restore-jobs/test/cfn-test-create-inputs.sh
- cfn-resources/cloud-backup-schedule/test/cfn-test-create-inputs.sh
- cfn-resources/cloud-backup-snapshot/test/cfn-test-create-inputs.sh
- cfn-resources/datalakes/test/cfn-test-create-inputs.sh
- cfn-resources/global-cluster-config/test/cfn-test-create-inputs.sh
- cfn-resources/online-archive/test/cfn-test-create-inputs.sh
- cfn-resources/search-index/test/cfn-test-create-inputs.sh
While releasing the search-index I noticed that the release process is using sleep 900 while waiting for cluster creation. This ticket is to update all these scripts to use atlas clusters watch
> INTMDB-629: [CFN-PI] Update CFN release process to use "atlas cluster watch"

- cfn-resources/network-container/cmd/resource/resource.go
- cfn-resources/network-container/resource-role.yaml
handling CANNOT_DELETE_RECENTLY_CREATED_CONTAINER error in network container DELETE handler.
> INTMDB 633 Network container delete handler hotfix

- cfn-resources/trigger/test/cfn-test-create-inputs.sh
Updating input params passed to create-test-inputs script for Trigger CFN resource based on how script is invoked when publishing.
> Fix params for create-test-inputs script for trigger

- cdk/cdk-resources/cloud-backup-schedule/API.md
- cdk/cdk-resources/cloud-backup-schedule/src/index.ts
- cdk/cdk-resources/cloud-backup-schedule/test/index.test.ts
In the Cloud Backup Schedule the ProjectId and ClusterName were set as read only and were not provided as an input Parameter
> Fixed CDK Cloud Backup Schedule read only properties

- cfn-resources/serverless-instance/docs/README.md
- cfn-resources/serverless-instance/mongodb-atlas-serverlessinstance.json
Updating the serverless name regex to use the same one used by the Atlas Public endpoint.
Link to any related issue(s): #369
> Fix serverless name input regex pattern

- cdk/cdk-resources/maintenance-window/API.md
- cdk/cdk-resources/maintenance-window/src/index.ts
- cfn-resources/maintenance-window/cmd/resource/resource.go
- cfn-resources/maintenance-window/docs/README.md
- cfn-resources/maintenance-window/mongodb-atlas-maintenancewindow.json
The next issues were fixed for Maintenance Window:
- ProjectId, AutoDeferOnceEnabled , were defined as readonly, making them inaccessible when generating the CDK
- Profile was not defined as PrimaryIdentifier, preventing the property to reach the READ
> Fixed maintenance window profile bug fix

- .github/workflows/code-health.yml
This is a follow-up PR of https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/430 where I merged all the code health checks into a single workflow. After merging my PR, the `dependency-review job` failed
on the push (see [7855956474](https://github.com/mongodb/mongodbatlas-cloudformation-resources/actions/runs/4471258467/jobs/7855956474)). The reason is that the action can be run only on pull requests. 
This PR fixes the workflow.
> INTMDB-682: update Dpendency-review to run only on pull requests

- MANUALQA.md
- TESTING.md.md
- cfn-resources/alert-configuration/test/README.md
This PR adds the [README.md](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/INTMDB-688/cfn-resources/alert-configuration/test) to the test folder of alert-configuration
> INTMDB-688: [CFN-PI] Add Manual QA for alert-configuration

- examples/quickstart-mongodb-atlas/execution-role.yaml
This PR adds the `execute-role.yaml` template to use to create the IAM role to run the quickstart template
**Next Steps:**
- Adding the same template in the aws repository
- Update the documentation to mention this template
> INTMDB-695: [CFN-PI] Quickstart VPC peering does not provide an iam role to use to execute the template

- cfn-resources/cloud-backup-snapshot/test/cfn-test-create-inputs.sh
- cfn-resources/custom-dns-configuration-cluster-aws/README.md
- cfn-resources/datalakes/test/cfn-test-create-inputs.sh
- cfn-resources/global-cluster-config/test/cfn-test-create-inputs.sh
- cfn-resources/global-cluster-config/test/inputs_1_create.template.json
- cfn-resources/global-cluster-config/test/inputs_1_invalid.template.json
- cfn-resources/network-container/test/networkcontainer.create-sample-cfn-request.sh
- cfn-resources/project-invitation/README.md
- cfn-resources/third-party-integration/README.md
- cfn-resources/third-party-integration/test/thirdpartyintegration.create-sample-cfn-request.sh
Remove MCLI_ env variables and cleanup READMEs for CFN resources
> Remove MCLI_ env variables and cleanup READMEs for CFN resources

- examples/profile-secret.yaml
Updating the example template for creating a profile secret to hide the private & public key values in the CFN UI
Example at creation:
Example of stack details:
works in Atlas
> INTMDB-724: Hide key values when using example profile template

- cdk/cdk-resources/cluster/src/index.ts
- cfn-resources/cluster/docs/README.md
The Cluster CDK L1, was modified to be able to output the connection strings:
the next properties were exposed by the CfnCluster.connectionStrings
- Standard
- StandardSrv
- Private
- PrivateSrv
expected)
works in Atlas
> added connection strings to Cluster CDK

- cfn-resources/network-container/cmd/resource/delete.go
The release process for network-container is failing with the error `"409 (request "CANNOT_DELETE_RECENTLY_CREATED_CONTAINER") Cannot delete containers created less than 1 second ago. Please try again after 2023-04-27T13:20:41.598Z."`
During my refactoring in #525, [this piece of code](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/525/files#r1179262091) was erroneously removed
This ticket is fixing this issue.
_Jira ticket:_ INTMDB-791
expected)
works in Atlas
```bash
cfn test
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== 11 …
```
> INTMDB-791: [CFN-PI] Handle error CANNOT_DELETE_RECENTLY_CREATED_CONTAINER during release

- cfn-resources/teams/README.md
- cfn-resources/teams/test/README.md
We're working to improve the overall documentation for CFN with Atlas. To that end, the docs team would like to first go through the READMEs for each resource like the one here and remove some duplicate and outdated information. Most of these changes we discussed with @andreaangiolillo.
We'd like to get the team's approval on this PR first. Then we can make the same changes for each resource, and reduce the review burden for engineers.
> DOCSP-29454 Clean up teams resource docs

- cfn-resources/cluster/cmd/resource/model.go
- cfn-resources/cluster/cmd/resource/resource.go
- cfn-resources/cluster/docs/advancedregionconfig.md
- cfn-resources/cluster/mongodb-atlas-cluster.json
- examples/cluster/cluster.json
- examples/cluster/project-cluster.json
Users were requesting we open the cluster creation to another providers, Originally the "ProviderName" property was close ONLY to AWS, now we allowed the users to input GCP, and AZURE
Link to any related issue(s): [HELP-46355](https://jira.mongodb.org/browse/HELP-46355)
expected)
works in Atlas
> added ProviderName to cluster

- cfn-resources/cloud-backup-schedule/cmd/resource/resource.go
- cfn-resources/cloud-backup-schedule/docs/README.md
- cfn-resources/cloud-backup-schedule/mongodb-atlas-cloudbackupschedule.json
Profile was made non required on Cloud Backup Schedule, in the other resources is optional and set as Default when not provided. we are replicating that behaviour in Cloud Buckup Schedule
_Jira ticket:_ CLOUDP-# https://jira.mongodb.org/browse/INTMDB-826
> INTMDB-826 removed profile as required filed

- cfn-resources/cluster/cmd/resource/model.go
- cfn-resources/cluster/cmd/resource/resource.go
- cfn-resources/cluster/mongodb-atlas-cluster.json
- examples/cluster/free-tier-M0-cluster.json
added support for for M0:
- Added new Provider Name "Tenant"
- Added new proerty required for Tenant, "BackingProviderName"
- Added validation to avoid calling the ProcessArgs when AdvancedSettings is not present
- Added example file
_Jira ticket:_ [INTMDB-905](https://jira.mongodb.org/browse/INTMDB-905)
cfn testing: 
expected)
works in Atlas
> added support for M0

- cfn-resources/ldap-verify/test/cfn-test-delete-inputs.sh
the ldap-verify does not contained a delete test script, so the resources remained after the resource had finished testing.
expected)
works in Atlas
> fix: ldap verify publishing script

- TESTING.md
- cfn-resources/organization/cmd/resource/resource.go
- cfn-resources/project/cmd/resource/resource.go
- cfn-resources/util/util.go
- cfn-resources/util/util_test.go
_Jira ticket:_ [INTMDB-1102](https://jira.mongodb.org/browse/INTMDB-1102)
Migrating project resource to new Atlas SDK.
**Note**: A potential bug was detected when verifying the update of API keys in the project resource. This bug is not related the sdk migration changes, verified with public extension that it is already present.
On creation, if an API key is defined it will be registered together with the key that is creating the project (defined with project owner permissions). When doing an update, the updated project api key defined is set correctly, but the default project owner key is removed. Created ticket [INTMDB-1128](https://jira.mongodb.org/browse/INTMDB-1128) to triage and see if we want to adjust this behaviour.
expected)
works in Atlas
**Automated E2E …
> refactor: Migrates Project resource to new Atlas SDK

- cfn-resources/search-index/cmd/resource/resource.go
- examples/search-index/searchIndex.json
_Jira ticket:_ [INTMDB-1157](https://jira.mongodb.org/browse/INTMDB-1157)
expected)
works in Atlas
<details>
<summary>Locally invoking lambda</summary>
Set of properties used:
```
{
"Profile": "default",
"ProjectId": "64c0f3f5ce752426ab9f506b",
"ClusterName": "cluster-name",
"Analyzer": "lucene.standard",
"CollectionName": "listingsAndReviews",
"Database": "sample_airbnb",
"Mappings": {
"Dynamic": "true"
},
"Name": "with-fix",
"SearchAnalyzer": "lucene.standard"
}
```
Following tests were run:
- creating index from master to see that dynamic config is not being set
- index with dynamic true
- index defining additional "Fields" property. As [per documentation](https://www.mongodb.com/docs/atlas/atlas-search/index-definitions/#review-fts-index-syntax), all fields are indexed if dynamic is …
> fix: properly set Dynamic property in search index mappings

- cfn-resources/ldap-verify/Makefile
- cfn-resources/ldap-verify/cmd/resource/resource.go
_Jira ticket:_ [INTMDB-1093](https://jira.mongodb.org/browse/INTMDB-1093)
Migrating LDAPVerify resource to new Atlas SDK.
expected)
works in Atlas
```
cfn test --function-name TestEntrypoint --verbose   
5 passed, 3 skipped, 16 deselected 
```
**Manual testing creating and deleting the stack using private registry:**
> refactor: Migrates LDAPVerify resource to new Atlas SDK

- cfn-resources/access-list-api-key/test/cfn-test-create-inputs.sh
- cfn-resources/api-key/test/cfn-test-create-inputs.sh
- cfn-resources/datalakes/test/cfn-test-create-inputs.sh
- cfn-resources/datalakes/test/cfn-test-delete-inputs.sh
- cfn-resources/federated-settings-org-role-mapping/test/cfn-test-create-inputs.sh
- cfn-resources/federated-settings-org-role-mapping/test/inputs_1_create.template.json
- cfn-resources/maintenance-window/docs/README.md
- cfn-resources/maintenance-window/mongodb-atlas-maintenancewindow.json
- cfn-resources/maintenance-window/test/cfn-test-create-inputs.sh
- cfn-resources/maintenance-window/test/inputs_1_create.template.json
- cfn-resources/maintenance-window/test/inputs_1_invalid.template.json
- cfn-resources/maintenance-window/test/inputs_1_update.template.json
- cfn-resources/private-endpoint-adl/test/cfn-test-create-inputs.sh
- cfn-resources/private-endpoint-adl/test/cfn-test-delete-inputs.sh
- cfn-resources/private-endpoint-adl/test/inputs_1_create.template.json
Fixed/Improvements deploy scripts for:
Apikeys - ApiKeysAccessLisy - there is a problem with the variables Atlas_org_id, i unified both of them
Maintenance-Widnow= profile was defined as CreateOnly, and it should be ReadOnly leadind to test failures
Datalakes: the project input variable was required for the atlas commands
Org Role Mapping: required to set an specific profile
PrivateEndpointADL: was expecting the user to provide a private endpoint, now the script is seting up the private endpoint itself
expected)
works in Atlas
> fix: fixed deploy for multiple resources

- cfn-resources/search-index/docs/README.md
- cfn-resources/search-index/mongodb-atlas-searchindex.json
in this issue https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/745 the user is trying to update the Mappings property.
Reading the SearchIndex documentation i see that Mappings is marked as Update requires: No interruption 
this means that if the user modifies this property, cloud formation should only execute the update, but reading the cloud formation template the Mapping property is marked as CreateOnly, (CreateOnly properties remplaces the resource when updated)
so when the user is trying to update this property, the resource gets replaced even tho the docs show otherwise.
This got solved by removing the properties that are not read only. 
_Jira ticket:_ [INTMDB-1163](https://jira.mongodb.org/browse/INTMDB-1163)
expected)
works in Atlas
> fix: INTMDB-1163 Changed create only properties 

- scripts/cleanup-test-env.sh
Jira ticket: [INTMDB-1123](https://jira.mongodb.org/browse/INTMDB-1123)
Maintain consistency with https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1516
expected)
works in Atlas
> chore: fix so cleanup-test-env script continues if delete of one project fails

- cfn-resources/search-index/mongodb-atlas-searchindex.json
Small fix of a warning when running cfn generate
"insertionOrder" : false was added to Fields array
was set to false, because the order on this field should not be taken into consideration when updating the resource. 
(it does not matter the order of the list, just the new elements)
test were passing with this new change
[INTMDB-1163](https://jira.mongodb.org/browse/INTMDB-1163)
expected)
works in Atlas
> fix: added insertion Order to SearchIndex

- .github/workflows/cfn-publish-resource.yaml
- .github/workflows/cfn-publish.sh
- .github/workflows/templates/params.json
- cfn-resources/cfn-publishing-automation/cfn-3P-provider-register.yaml
Change publishing AWS SSM Doc:
- Support a specific publishing version, support base_url. Change AWS SSM doc to receive and give the publishing version variable  PUBLISHING_RESOURCE_VERSION.
- Update from Go 1.18 to 1.20
- Support base_url
- Add default values
- Simplify SSM doc
expected)
works in Atlas
Publishing ldap-verify resource type continues working fine
> feat: AWS automation update: v54 [publish version, base url] 

- .github/workflows/code-health.yaml
Jira ticket: [INTMDB-1244](https://jira.mongodb.org/browse/INTMDB-1244)
Disables linter cache, similar to: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1555
> feat: Fixes linter cache

- cfn-resources/cloud-backup-snapshot/cmd/resource/model.go
- cfn-resources/cloud-backup-snapshot/cmd/resource/resource.go
- cfn-resources/cloud-backup-snapshot/docs/README.md
- cfn-resources/cloud-backup-snapshot/mongodb-atlas-cloudbackupsnapshot.json
- cfn-resources/cloud-backup-snapshot/test/cfn-test-create-inputs.sh
- cfn-resources/cloud-backup-snapshot/test/cfn-test-delete-inputs.sh
- cfn-resources/cloud-backup-snapshot/test/inputs_1_create.template.json
- examples/cloud-backup-snapshot/snapshot.json
The original configuration of the Cloud Backup Snapshot resource included properties for ClusterName and InstanceName. However, this setup led to errors during read operations, as only ClusterName served as a primary identifier. When InstanceName was specified instead of ClusterName, it resulted in primary identifier errors.
To rectify this, the following modifications have been implemented:
Removal of ClusterName:
The ClusterName property, which posed challenges due to its exclusive primary identifier status, has been removed from the configuration. This change eliminates the confusion arising from the presence of both ClusterName and InstanceName.
InstanceName as Primary Identifier:
The InstanceName property now takes center stage as the primary identifier for the Cloud Backup Snapshot. …
> fix!: INTMDB-1175 fixed cloud Backup snapshot primary identifier

- cfn-resources/alert-configuration/cmd/resource/resource.go
- cfn-resources/org-invitation/cmd/resource/resource.go
- cfn-resources/project-invitation/cmd/resource/resource.go
- cfn-resources/test/e2e/project/project_test.go
- cfn-resources/test/e2e/utility/atlas_helper.go
- cfn-resources/test/e2e/utility/util.go
- cfn-resources/util/util.go
- cfn-resources/x509-authentication-database-user/cmd/resource/resource.go
_Jira ticket:_ [INTMDB-1243](https://jira.mongodb.org/browse/INTMDB-1243)
This PR includes the following changes to remove left over usages of old sdk, with the end goal of removing the old sdk dependency from the project:
- migrate all usages of old sdk in e2e tests utilities
- remove unused code in `cfn-resources/x509-authentication-database-user`
- fix code in alert-configuration that was using old sdk struct for a comparison operation.
- refactor delete operation in `org-invitation` which was not migrated.
- refactor get operation in `project-invitation` which was not migrated.
expected)
works in Atlas
<details>
<summary>Running e2e locally to verify all operations work well</summary>
```
util.go:62: E2E test resource type MongoDB::Atlas::Project6820 successfully de-registered from …
```
> refactor: remove usages of old sdk in e2e tests and resources where usage was unintentionally left

- cfn-resources/cloud-backup-restore-jobs/docs/README.md
- cfn-resources/cloud-backup-restore-jobs/mongodb-atlas-cloudbackuprestorejobs.json
Some properties were missing on the Required fields tag on the Cloud Backup Restore Job resource:
"InstanceName",
"InstanceType",
"SnapshotId",
"DeliveryType"
where added to the the required section
_Jira ticket:_ [INTMDB-1227](https://jira.mongodb.org/browse/INTMDB-1227)
expected)
works in Atlas
> fix: INTMDB-1227 Cloud Backup Restore Job added required props

- cfn-resources/project/cmd/resource/resource.go
- cfn-resources/project/docs/README.md
- cfn-resources/project/mongodb-atlas-project.json
- cfn-resources/project/resource-role.yaml
- cfn-resources/project/test/cfn-test-create-inputs.sh
- cfn-resources/project/test/contract-testing/cfn-test-create-inputs.sh
fix: Project schema change to fix the name update issue.
JIRA Ticket: https://jira.mongodb.org/browse/INTMDB-1203
Changes:
Removed name from createOnly property
expected)
works in Atlas
> fix: project name update is fixed

- cfn-resources/auditing/resource-role.yaml
- cfn-resources/datalakes/resource-role.yaml
- examples/execution-role.yaml
fix: emoved unwanted secrets manager permissions
JIRA Ticket: https://jira.mongodb.org/browse/INTMDB-1001
expected)
works in Atlas
> fix: removed unwanted secrets manager permissions

- scripts/cleanup-test-env.sh
Jira ticket: [INTMDB-1399](https://jira.mongodb.org/browse/INTMDB-1399)
Increases project list limit for clean-up Github action.
expected)
works in Atlas
> chore: Increases project list limit for clean-up Github action

- cfn-resources/scripts/update-sdk.sh
CLOUDP-221977
Using latest is known to cause cache issues with go.dev, using directly the tag should help reduce those problems.
same change as: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1885
> chore: New released Atlas Go SDK can't be used until several hours later

- .github/workflows/cleanup-test-env.yml
Removes CFN Test from cleanup process
expected)
works in Atlas
> chore: Removes CFN Test from cleanup process

- .tool-versions
Small cleanup of .tool-versions
expected)
works in Atlas
> chore: Removes nodejs (typo in file) nodejs is no longer used

- cfn-resources/alert-configuration/cmd/resource/resource.go
The MicrosoftTeamsWebhookUrl property is not copied into alert notification configurations.
works in Atlas
> fix: Add missing MicrosoftTeamsWebhookUrl to alert notification configuration

- cfn-resources/tool/cfn-publishing-automation/cfn-3P-provider-register.yaml
Makes automation script less verbose by adding -q flags to wget and unzip
expected)
works in Atlas
> chore: Makes automation script less verbose

- cfn-resources/federated-database-instance/cmd/resource/resource.go
- cfn-resources/federated-database-instance/docs/dataprocessregion.md
- cfn-resources/federated-database-instance/mongodb-atlas-federateddatabaseinstance.json
- cfn-resources/federated-database-instance/test/data-federation-sample-request.json
- cfn-resources/util/util.go
Fixes bug where creation of resource was not possible without setting values for optional attributes DataProcessRegion and CloudProviderConfig.
Now it's possible to create a `FederatedDatabaseInstance` without setting those attributes
Some opportunistic improvements in the code have been maded in the resource.
Link to any related issue(s): CLOUDP-219922
expected)
works in Atlas
Tests results:
Stack creation and update:
Atlas UI after creation:
> fix: Allows not setting optional attributes DataProcessRegion and CloudProviderConfig for `FederatedDatabaseInstance`

- cfn-resources/federated-database-instance/cmd/resource/resource.go
Fixes pointer dereference when specifying `CloudProvider` in `DataProcessRegion`
Link to any related issue(s): CLOUDP-219922
expected)
works in Atlas
> fix: Fixes pointer dereference when specifying `CloudProvider` in `DataProcessRegion`

- cfn-resources/access-list-api-key/cmd/resource/resource.go
- cfn-resources/api-key/cmd/resource/resource.go
- cfn-resources/data-lake-pipeline/cmd/resource/resource.go
- cfn-resources/federated-query-limit/cmd/resource/resource.go
- cfn-resources/privatelink-endpoint-service-data-federation-online-archive/cmd/resource/resource.go
- Remove defer closeResponse because this is already being done in the SDK
- Refactor requests
expected)
works in Atlas
> chore: Removes defer closeResponse

- cfn-resources/access-list-api-key/CHANGELOG.md
- cfn-resources/access-list-api-key/cmd/resource/model.go
- cfn-resources/access-list-api-key/cmd/resource/resource.go
- cfn-resources/access-list-api-key/docs/README.md
- cfn-resources/access-list-api-key/mongodb-atlas-accesslistapikey.json
_Jira ticket:_ CLOUDP-250925
Defines a new read only property `Entry` that is included as part of the primary id of the access-list-api-keys resource. The value of this property is simply `IdAddress` or `CidrBlock` which are required and mutually exclusive (validated during the create operation).
Why not include `IdAddress` and `CidrBlock` directly as part of the primary id? When trying this approach the following error is encountered because one of these properties will be empty and this is not supported by CFN (all primary id properties must be present):
`Create handler did not return the primaryIdentifier for the physical resource`
Example stack:
```
"Resources": {
"FirstAPIKeyEntry": {
"Type": "MongoDB::Atlas::AccessListAPIKey",
"Properties": {
"OrgId": "64b6bf4c1f89ae5ca0f0d849", …
```
> fix: Enable defining multiple access-list-api-keys resources in a single stack

- .github/workflows/e2e-testing.yaml
- cfn-resources/cluster/cmd/resource/mappings.go
- cfn-resources/cluster/cmd/resource/mappings_test.go
- cfn-resources/cluster/cmd/resource/resource.go
- cfn-resources/test/e2e/cluster/cluster.json.template
- cfn-resources/test/e2e/cluster/cluster_test.go
- cfn-resources/util/util.go
1. Adds e2e test for cluster
2. Fix: Edits to replication specs for cluster
1. Create a GEOSHARDED cluster with a single replication spec (zone1) with 3 nodes
2. Update the cluster:
- Change from 3->5 nodes in zone1
- Add a new replication spec (zone2) with 5 nodes
3. Assert the replication_id is kept on the 1st replication spec, and a new replication spec is added and both replication specs have 5 nodes
The fix reads the current cluster if replication specs are set and "matches" replication IDs.
See the unit tests in  [`mappings_test`](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/CLOUDP-256534_replication_id_matching/cfn-resources/cluster/cmd/resource/mappings_test.go#L26) for the matching details.
Note: We couldn't reuse the Terraform implementation since CFN …
> fix: Edits to replication specs for cluster

- cfn-resources/federated-query-limit/mongodb-atlas-federatedquerylimit.json
Removes duplicated `DefaultLimit` in `federated-query-limit` read-only properties
expected)
works in Atlas
> fix: Removes duplicated `DefaultLimit` in `federated-query-limit` read-only properties

- Makefile
- cfn-resources/cfn-publish.sh
Fixes the pagination for aws cloudformation list-type-versions
Link to any related issue(s): CLOUDP-268623
Relevant failing logs from s3 (similar execution role is used in all the 3 failed attempts):
```
[2024-08-19T09:12:43Z] DEBUG    - Running test: Namespace(version=False, subparser_name='test', command=<function test at 0x7fcd23c795e0>, verbose=0, endpoint='<https://lambda.ap-northeast-2.amazonaws.com>', function_name='MongoDB-Atlas-Cluster711489243244-Handler-1u0hypumvwcoc', region='ap-northeast-2', profile=None, role_arn='arn:aws:iam::711489243244:role/mongodb-atlas-cluster-role-stack-ExecutionRole-Ae24TDEYnNlX', cloudformation_endpoint_url=None, enforce_timeout='240', log_group_name=None, log_role_arn=None, passed_to_pytest=[], docker_image=None, typeconfig=None, …
```
> chore: Fixes the pagination for aws cloudformation list-type-versions

- cfn-resources/.golangci.yml
Updates exclude-rules in Go linter.
Follow-up PR from this comment https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/1144#discussion_r1743736922
expected)
works in Atlas
> chore: Updates exclude-rules in Go linter

- .github/workflows/publish.yaml
- cfn-resources/cfn-publishing-helper.sh
Uses QA environmnet when publishing resource-policy
Link to any related issue(s): CLOUDP-272615
expected)
works in Atlas
> chore: Uses QA environment when publishing resource-policy

- cfn-resources/resource-policy/docs/README.md
- cfn-resources/resource-policy/docs/apiatlaspolicy.md
- cfn-resources/resource-policy/mongodb-atlas-resourcepolicy.json
resource-policy schema, mark required attributes
Link to any related issue(s): CLOUDP-275212
expected)
works in Atlas
> fix: resource-policy schema, mark required attributes

- cfn-resources/project/docs/README.md
- cfn-resources/project/mongodb-atlas-project.json
Removes `ProjectOwnerId` from read only properties in `Project`
Link to any related issue(s): CLOUDP-274173
expected)
works in Atlas
> chore: Removes `ProjectOwnerId` from read only properties in `Project`

- cfn-resources/resource-policy/mongodb-atlas-resourcepolicy.json
- cfn-resources/resource-policy/resource-role.yaml
Fixes resource permissions for resource-policy
Link to any related issue(s): CLOUDP-277131
expected)
works in Atlas
> fix: Fixes resource permissions for resource-policy

- examples/execution-role.yaml
Adds ec2:DescribeVpcEndpoints to make examples/private-endpoint/privateEndpointV2.json work
expected)
works in Atlas
> doc: Adds ec2:DescribeVpcEndpoints to make examples/private-endpoint/privateEndpointV2.json work

- cfn-resources/database-user/cmd/resource/resource.go
- cfn-resources/database-user/test/inputs_2_update.template.json
Set scopes in Read to support Scope updates
Link to any related issue(s): CLOUDP-287006 #1233 
expected)
works in Atlas
> fix: Sets scopes in Read to support Scope updates

- README.md
- cfn-resources/README.md
- cfn-resources/private-endpoint/upgradeguidev2/V2-UpgradeGuide.md
Documentation changes to add information on the Import functionality
Link to any related issue(s): CLOUDP-303586
expected)
works in Atlas
> doc: Import support documentation and considerations

- README.md
- cfn-resources/cloud-backup-snapshot-export-bucket/resource-role.yaml
- cfn-resources/custom-db-role/resource-role.yaml
- cfn-resources/global-cluster-config/resource-role.yaml
- examples/README.md
Updates README with details on AWS Secrets Manager profile naming for CloudFormation
Link to any related issue(s): HELP-72416
expected)
works in Atlas
> doc: Updates README with details on AWS Secrets Manager profile naming for CloudFormation

- cfn-resources/trigger/mongodb-atlas-trigger.json
- cfn-resources/trigger/test/README.md
- cfn-resources/trigger/test/inputs_1_create.template.json
- cfn-resources/trigger/test/inputs_1_update.template.json
- cfn-resources/util/constants/constants.go
Renames "realm" occurrences to App Services. Cleaning up wherever required.
_Jira ticket:_ [CLOUDP-273338](https://jira.mongodb.org/browse/CLOUDP-273338)
expected)
works in Atlas
> chore: Renames "realm" occurrences to App Services

- README.md
- examples/README.md
Enhances README with additional MongoDB Atlas and AWS CloudFormation documentation links and resource support details
Link to any related issue(s): CLOUDP-307844
expected)
works in Atlas
> doc: Enhances README with additional MongoDB Atlas and AWS CloudFormation documentation links and resource support details

- cfn-resources/database-user/cmd/resource/model.go
- cfn-resources/database-user/cmd/resource/resource.go
- cfn-resources/database-user/docs/README.md
- cfn-resources/database-user/mongodb-atlas-databaseuser.json
- cfn-resources/database-user/test/cfn-test-create-inputs.sh
- cfn-resources/database-user/test/inputs_1_create.template.json
- cfn-resources/database-user/test/inputs_1_update.template.json
- cfn-resources/database-user/test/inputs_2_create.template.json
- cfn-resources/database-user/test/inputs_2_update.template.json
- examples/database-user/scramUser.json
Adds `Description` to MongoDB::Atlas::DatabaseUser
Link to any related issue(s): CLOUDP-288714
expected)
works in Atlas
Example manual run:
> feat: Adds `Description` to MongoDB::Atlas::DatabaseUser

- .github/workflows/code-health.yaml
- Makefile
- cfn-resources/.golangci.yml
- cfn-resources/go.mod
- cfn-resources/project/Makefile
- cfn-resources/util/util.go
Update Go to 1.25.0.
Also updated Go linter to 2.4.0.
expected)
works in Atlas
> chore: Update Go to 1.25.0

- cfn-resources/flex-cluster/test/cfn-test-create-inputs.sh
- cfn-resources/flex-cluster/test/cfn-test-delete-inputs.sh
- cfn-resources/flex-cluster/test/contract-testing/cfn-test-create.sh
Fix publish in FlexCluster. Publish scripts expect the project name not the project id as the first parameter.
_Jira ticket:_ CLOUDP-342254
expected)
works in Atlas
> chore: Fix publish in FlexCluster

- cfn-resources/cluster/README.md
- examples/cluster/README.md
- Updates cfn-resources README file
- Updates examples/cluster/README file
_Jira ticket: https://jira.mongodb.org/browse/DOCSP-53419
Link to any related issue(s): https://jira.mongodb.org/browse/CLOUDP-286685
expected)
works in Atlas
> doc: DOCSP-53419 Update doc for MongoDB::Atlas::Cluster CFN resource
